directory_name: 'dir_test'
# analysis_event_type: 'MY_PYTHIA_PATH_2' 
analysis_event_type: 'OFFICIAL_NCDIS_PYTHIA_epic_VER25_1_0' 
# FILE_PATH_NCDIS_LARGE or FILE_PATH_SINGLE_PARTICLE_PION_OLDVERSION or FILE_PATH_SINGLE_PARTICLE_KAON_OLDVERSION or MYPYTHIA_FILE_PATH
VERBOSE: True
PLOT_VERBOSE: True
DETAIL_PLOT_VERBOSE: False

SELECTED_EVENTS: 10000

#konosita mada mizissou
VERTEX_X_MIN: 20
VERTEX_X_MAX: 30
VERTEX_Y_MIN: 20
VERTEX_Y_MAX: 30
VERTEX_Z_MIN: 20
VERTEX_Z_MAX: 30