directory_name: 'eicrecon_ver2501_NCDIS_N50000_th_01'
analysis_event_type: 'FILE_PATH_VER2501_NCDIS' 
# analysis_event_type: 'FILE_PATH_SINGLE_PARTICLE_PION_NEW' 
# FILE_PATH_NCDIS_LARGE or FILE_PATH_SINGLE_PARTICLE_PION_OLDVERSION or FILE_PATH_SINGLE_PARTICLE_KAON_OLDVERSION or MYPYTHIA_FILE_PATH
VERBOSE: True
PLOT_VERBOSE: True
DETAIL_PLOT_VERBOSE: False

SELECTED_EVENTS: 50000

#konosita mada mizissou
VERTEX_X_MIN: 20
VERTEX_X_MAX: 30
VERTEX_Y_MIN: 20
VERTEX_Y_MAX: 30
VERTEX_Z_MIN: 20
VERTEX_Z_MAX: 30